version: '3.8'

services:
  redis:
    image: redis
    container_name: cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_name
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  redis_data:
